In [3]:
import os
import numpy
from PIL import Image

In [18]:
data_matrix = numpy.ndarray(shape=(400, 10304), dtype=numpy.dtype('u1'))  # 8-bit unsigned int
label_vector = numpy.empty(shape=(400,1), dtype=numpy.dtype('u1'))

i = 0
for dirname, _, filenames in os.walk('dataset'):
    for filename in filenames:
        image = Image.open(os.path.join(dirname, filename))
        numpy_image = numpy.asarray(image).flatten()
        data_matrix[i] = numpy_image.copy()
        label_vector[i] = int(dirname[dirname.rindex('\\')+ 2:])
        i += 1

print(data_matrix)

[[ 48  49  45 ...  47  46  46]
 [ 34  34  33 ...  37  40  33]
 [ 60  60  62 ...  32  34  34]
 ...
 [112 109 116 ...  93  88  92]
 [111 114 112 ...  88  86  92]
 [110 112 113 ...  92  87  90]]


In [24]:
# Odd rows for training
train_data = data_matrix[::2,:]
train_label = label_vector[::2,:]

# Even rows for testing
test_data = data_matrix[1::2,:]
test_labels = label_vector[1::2,:]

print(test_data)
print("\n")
print(train_data)

[[ 34  34  33 ...  37  40  33]
 [ 39  44  53 ...  29  26  29]
 [ 64  76  80 ...  35  37  39]
 ...
 [110 109 111 ...  94  88  90]
 [112 109 116 ...  93  88  92]
 [110 112 113 ...  92  87  90]]


[[ 48  49  45 ...  47  46  46]
 [ 60  60  62 ...  32  34  34]
 [ 63  53  35 ...  41  10  24]
 ...
 [114 110 112 ...  93  89  86]
 [113 112 111 ...  87  87  89]
 [111 114 112 ...  88  86  92]]


In [30]:
# PCA
mean = numpy.mean(train_data,axis=0)
print(mean)
print("\n")
centered_data = numpy.subtract(train_data,mean)
print(centered_data)
print("\n")
cov_matrix = numpy.cov(centered_data)
print(cov_matrix)
print("\n")
eigen_values , eigen_vectors = numpy.linalg.eigh(cov_matrix)
print(eigen_values)
print("\n")
print(eigen_vectors)
print("\n")

[84.97  84.79  85.055 ... 76.39  73.815 72.215]


[[-36.97  -35.79  -40.055 ... -29.39  -27.815 -26.215]
 [-24.97  -24.79  -23.055 ... -44.39  -39.815 -38.215]
 [-21.97  -31.79  -50.055 ... -35.39  -63.815 -48.215]
 ...
 [ 29.03   25.21   26.945 ...  16.61   15.185  13.785]
 [ 28.03   27.21   25.945 ...  10.61   13.185  16.785]
 [ 26.03   29.21   26.945 ...  11.61   12.185  19.785]]


[[1159.59401922  108.33626297  239.89842181 ...   -5.24374551
  -140.43034387  -51.44006705]
 [ 108.33626297 1338.54933411   21.88078478 ... -465.967358
  -375.19137309 -426.47063346]
 [ 239.89842181   21.88078478 1965.33308775 ... -276.76278548
  -352.28398422 -355.49559413]
 ...
 [  -5.24374551 -465.967358   -276.76278548 ... 1024.67923872
   576.94669186  667.12266488]
 [-140.43034387 -375.19137309 -352.28398422 ...  576.94669186
  1152.63562869  601.75569142]
 [ -51.44006705 -426.47063346 -355.49559413 ...  667.12266488
   601.75569142 1009.603827  ]]


[-3.30968860e-12  5.29766381e+01  6.82301147e+01